global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bitcoin_node'
    # Bitcoin Core doesn't expose metrics directly
    # You'll need an exporter like bitcoin-exporter
    static_configs:
      - targets: ['bitcoin-node:8332']
    metrics_path: '/metrics'
    scheme: http

  - job_name: 'lnd_node'
    # LND requires TLS and macaroon authentication
    static_configs:
      - targets: ['lnd-node:8080']
    metrics_path: '/metrics'
    scheme: https

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'bitcoin_exporter'
    static_configs:
      - targets: ['bitcoin-exporter:9332']
    metrics_path: '/metrics'
    scheme: http
